name: flutter_application_1
description: A blockchain Flutter DApp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  web3dart: ^2.6.1        # Version disponible
  http: ^0.13.5           # Version compatible avec 2.x
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - src/artifacts/HelloWorld.json